Django3/urls.py
from django.contrib import admin
from app03 import views
from webqq import urls as chat_urls
from django.conf.urls import url, include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^host/$', views.host, name='host'),
    url(r'^asset/$', views.asset, name='asset'),
    url(r'^audit/$', views.audit, name='audit'),
    url(r'^accounts/login/$', views.acc_login, name='login'),
    url(r'^logout/$', views.acc_logout, name='logout'),
    url(r'^article/(\d+)/$', views.article, name='article'),
    url(r'^create_article/$', views.create_article, name='create_article'),
    url(r'^chat/', include(chat_urls)),
]

webqq/urls.py
from webqq import views
from django.conf.urls import url, include


urlpatterns = [
    url(r'^$', views.dashboard, name='chat'),
    url(r'^send_msg/$', views.send_msg, name='chat_send_msg'),
    url(r'^get_msg/$', views.get_msg, name='get_new_msg'),

]

app03/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.

#开始建表了，这个项目是为了设计bbs论坛的表结构

class Article(models.Model):
    title = models.CharField(max_length=64)          #文章标题
    category = models.ForeignKey('Category')         #板块与文章是一对多关系，从文章表角度来看，这个是多对一
    content = models.TextField(max_length=100000)     #文章内容是不固定的，也就是会很多，这个不填是想多少就多少
    author = models.ForeignKey('Userprofile')         #作者与文章也是多对一关系
    #thumb_up = models.ForeignKey('ThumbUp', blank=True)     #点赞 和 文章是多对一关系,这里其实错了，不能多对一，只能一对多
    #comments = models.ManyToManyField('Comment', blank=True)  ##点赞 和 文章是多对一关系,这里其实错了，不能多对一，只能一对多
    head_img = models.ImageField(upload_to='static/imgs/uploadCom')
    publish_date = models.DateTimeField(auto_now_add=True)  #文章创建时间是固定的，自动填写
    summary = models.CharField(max_length=500)  ##文章索引内容

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)       #板块名字
    admins = models.ManyToManyField('UserProfile')          #版主信息，版主管理多个板块，板块有多个版主
    def __str__(self):
        return self.name

class ThumbUp(models.Model):
    artile = models.ForeignKey('Article')    ##一个文章可以有多个赞
    user = models.ForeignKey('UserProfile')    ##一个用户可以点多个赞
    date = models.DateTimeField(auto_now_add=True) ##点赞的时间

    def __str__(self):
        return self.artile.title            #这个返回了article表的数据

class Comment(models.Model):
    artile = models.ForeignKey('Article')    ##一个评论可以有多个赞
    comments_title = models.CharField(max_length=32)  ##评论标题
    user = models.ForeignKey('UserProfile')    ##一个评论可以点多个赞
    comments = models.TextField(max_length=1024) ##评论内容很多
    date = models.DateTimeField(auto_now_add=True)  ##评论的时间

    ###这里有个多级评论，就是几楼几楼那种，你可以评论几楼，这样评论与评论之家，就有了关联,
    ##这里就成自关联！！！自关联必须加related_name

    ##这里两个blank null为 True，意思就是 admin前端 界面 不让为空，数据库存储时不让为空
    parent_comment = models.ForeignKey('Comment', blank=True, null=True, related_name='pid')

    def __str__(self):
        return self.comments_title


class UserProfile(models.Model):
    user = models.OneToOneField(User)                   #继承系统自带用户表,一对一关系
    name = models.CharField(max_length=32)      #名字可以重名
    user_groups = models.ManyToManyField('UserGroup')

    friends = models.ManyToManyField('self', blank=True, related_name='my_friends')


    def __str__(self):
        return self.name

class UserGroup(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

webqq/models.py
from django.db import models
from app03 import models as bbs_models

# Create your models here.

class QQGroup(models.Model):
    name = models.CharField(max_length=64)
    #关联同一张表多次，必须有related_name
    founder = models.ForeignKey(bbs_models.UserProfile)
    brief = models.TextField(max_length=1024, default='nothing....')
    admin = models.ForeignKey(bbs_models.UserProfile, related_name='group_admins')
    members = models.ManyToManyField(bbs_models.UserProfile, related_name='group_members')
    member_limit = models.IntegerField(default=200)

    def __str__(self):
        return self.name

app03/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from app03 import models, utils
# Create your views here.

#
# def index(request):
#     articles = models.Article.objects.all().order_by('publish_date')
#
#
#     return render(request, 'index.html', {
#         'articles': articles
#     })


def article(request, article_id):
    #文章随便写是找不到的
    err_msg = ''
    try:
        article_obj = models.Article.objects.get(id=article_id)
        comments = utils.build_comments_tree(request)
    except BaseException as e:
        err_msg = str(e)

    return render(request, 'article.html', {
        'article': article_obj,
        'err_msg': err_msg,
        'comments': comments
    })

def create_article(request):

    if request.method == 'GET':
        return render(request, 'create_article.html')
    elif request.method == 'POST':
        print(request.FILES, "-------<<<<<")

        #为了bbs的创建，修改（多次），删除等，专门写一个类来处理
        #放在utlis中，utlis在APP中

        bbs_generater = utils.ArticleGen(request)
        res = bbs_generater.create()
        html_ele = ''' Your article [ <a href='/article/%s'>%s</a> ] has been created sucessfully''' % (res.id, res.title)

        return HttpResponse(html_ele)




def host(request):
    return render(request, 'article.html')

def asset(request):

    return render(request, 'create_article.html')


def audit(request):
    return render(request, 'audit.html')

def acc_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None: #pass authentication
            login(request, user)
            return HttpResponseRedirect('/')
        else: ##密码不对
            return render(request, 'login.html', {
                'login_error': 'Worng username or password',
            })

    else:
        return render(request, 'login.html')

def acc_logout(request):
    logout(request)
    return HttpResponseRedirect("/")



def index(request):
    article_list = models.Article.objects.order_by('publish_date')
    paginator = Paginator(article_list, 2) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles = paginator.page(paginator.num_pages)

    return render(request, 'index.html', {
        'articles': articles
    })

webqq/views.py
from django.shortcuts import render, HttpResponse
from webqq import models, utils
import json, datetime
# Create your views here.


# 全局字典，检测是否有数据，这个用来应对不同进程的queue保存的数据不一样。
global_msg_dic = {}


def dashboard(request):

    # print(models.QQGroup.name)

    #单独建立一个 templates webqq项目,里面放置对应的 webqq的html内容
    return render(request, 'webqq/dashboard.html')


def send_msg(request):
    print("okoko")
    print(request.POST)
    data = request.POST.get("data")
    print(json.loads(data))

    #序列化python能认识的字典
    data = json.loads(data)

    # #给数据打上时间戳
    data['date'] = datetime.datetime.now().strftime("%Y%m%d %H%M%S")

    #数据从前端取出
    to_id = data.get('to_id')
    contact_type = data.get('contact_type')
    user_obj = models.bbs_models.UserProfile.objects.get(id=to_id)

    #如果给单个人发消息
    if contact_type == 'single':

    ##开始调用关于消息的类，多用这种，面向对象
        if not to_id in global_msg_dic:
            global_msg_dic[to_id] = utils.Chat()

        global_msg_dic[to_id].msg_queue.put(data)

        print("Push msg [%s] into user [%s] queue" % (data['msg'], user_obj))


    return HttpResponse("ddddddddddddddddd")


#把后台收到的消息扔
def get_msg(request):
    uid = request.GET.get('uid')
    if uid:
        res = []

        #没有就创建一个
        if not uid in global_msg_dic:
            global_msg_dic[uid] = utils.Chat()


        res = global_msg_dic[uid].get_msg(request)
        return HttpResponse(json.dumps(res))
    else:
        return HttpResponse(json.dumps("uid not provided!"))

templates/article.html
{% extends 'index.html' %}
{% load custom %}
{% block content_left %}
    <div class="container">
         <div class="col-lg-8">
             <h3>{{ article.title }}</h3>
             <div class="blog_head_btn">
             <div class="blog_head_btn">
                <span>Author:{{ article.author.name }}</span>
                <span>Time:{{ article.publish_date }}</span>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
                {# 反查评论数#}
                <span><i class="fa fa-comment-o"></i> {{ article.comment_set.select_related.count }}</span>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
                <span><i class="fa fa-wechat"></i> {{ article.thumbup_set.select_related.count }}</span>
             </div>

             <div class="blog-content">
                    <span>{{ article.content|safe }}</span>

                 </div>
             </div>

             <div class="blog-content">
                 <hr/>
                 {% build_comment_tree comments %}
             </div>
    </div>
{% endblock %}

templates/audit.html
{% extends 'index.html' %}

{% block left_content %}

    <h2> hahahha </h2>

{% endblock %}

{% block right_content %}
    <h3>Audit Page</h3>
{% endblock %}

templates/create_article.html
{% extends 'index.html' %}
{% block content_left %}


{#    #内容，是bbs的编辑器#}
    <div class="container">
         <div class="col-lg-8">



             <form class="form-horizontal" method="post" action="{% url 'create_article' %}" enctype="multipart/form-data"> {% csrf_token %}
              <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">文章标题</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" name="title">
                </div>
              </div>





              <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">文章简介</label>
                <div class="col-sm-10">
                  <textarea class="form-control" rows="4" name="summary"></textarea>
                </div>
              </div>

             <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">标题图片</label>
                <div class="col-sm-10">
                  <input type="file" name="head_img"/>
                </div>
              </div>



              <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">内容</label>
                <div class="col-sm-10">
                  <textarea id="create_bbs" name="content"></textarea>
                </div>
              </div>


{#              <div class="form-group">#}
{#                <div class="col-sm-offset-2 col-sm-10">#}
{#                  <div class="checkbox">#}
{#                    <label>#}
{#                      <input type="checkbox"> Remember me#}
{#                    </label>#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
{#                 #}
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-default">创建</button>
                </div>
              </div>

            </form>

         </div>
    </div>





{% endblock %}

{% block bottom_js %}
    <script src="/static/plugins/tinymce/js/tinymce/tinymce.min.js"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "#create_bbs" {# ##需要自己定义textarea #}
        });


    </script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BBS</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="/static/css/customs.css" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="/static/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet">

</head>



<body>

    <header class="navbar navbar-static-top bs-docs-nav" id="top">
      <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">PPPP Stage</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">首页</a></li>
            <li><a href="{% url 'host' %}">主机</a></li>
            <li><a href="{% url 'asset' %}">资产</a></li>
            <li><a href="{% url 'chat' %}">聊天室</a></li>
          </ul>

          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>

          <ul class="nav navbar-nav navbar-right" >
                <li>
                    {% if request.user.is_authenticated %}
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user }} <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="{% url 'logout' %}">登出</a></li>
                          </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'login' %}">登陆</a></li>
                    {% endif %}
                </li>
                <li><a href="#">注册</a></li>
            </ul>
        </div>
      </div>
    </nav>
    </header>

{% block content_left %}
    <div class="container">

      {% for artile in articles%}
          <div class="col-lg-8">
            <hr/>
              <div class="blog-box row">
                    <div class="head-img col-md-4">
                        <img src="{{ artile.head_img }}">
                    </div>

                    <div class="bolg-summary-box col-md-8">
                        <h3><a href="{% url 'article' artile.id %}">{{ artile.title }}</a></h3>

                        <div class="blog-summary-btn">
                            {{ artile.author.name }}|{{ artile.publish_date }}
                        </div>

                        <div class="blog-summary">
                            {{ artile.summary }}
                            <span><i class="fa fa-wechat"></i></span> 4&nbsp;&nbsp;&nbsp;&nbsp;|
                            <span><i class="fa fa-comment-o" aria-hidden="true"></i></span> 7&nbsp;&nbsp;&nbsp;&nbsp;|
                            <span><i class="fa fa-bicycle" aria-hidden="true"></i></span> 11&nbsp;&nbsp;&nbsp;&nbsp;



                        </div>



                    </div>

              </div>

          </div>

      {% endfor %}


        <div class="col-md-2">
            ddfdfds
        </div>



    </div>


{#    Django自带的抄的#}
{#    <div class="pagination">#}
{#        <span class="step-links">#}
{#            {% if articles.has_previous %}#}
{#                <a href="?page={{ articles.previous_page_number }}">previous</a>#}
{#            {% endif %}#}
{##}
{#            <span class="current">#}
{#                Page {{ articles.number }} of {{ articles.paginator.num_pages }}.#}
{#            </span>#}
{##}
{#            {% if articles.has_next %}#}
{#                <a href="?page={{ articles.next_page_number }}">next</a>#}
{#            {% endif %}#}
{#        </span>#}
{#    </div>#}

{#    更改的#}

<div class="container">
    <div class="col-lg-8">
        <hr/>
        <nav aria-label="...">
          <ul class="pagination">


{#            如果有上一页#}
            {% if articles.has_previous %}
              <li><a href="?page={{ articles.previous_page_number }}"><span>&laquo;</span></a></li>
            {% endif %}

{#            当前页显示#}
            {% for p_num in articles.paginator.page_range %}
              {% if p_num == articles.number %}
                <li class="active"><a href="?page={{ p_num }}">{{ p_num}}<span class="sr-only">(current)</span></a></li>
              {% else %}
                <li><a href="?page={{ p_num }}">{{ p_num}}<span class="sr-only">(current)</span></a></li>
              {% endif %}
            {% endfor %}

            {#如果有下一页#}
            {% if articles.has_next %}
              <li><a href="?page={{ articles.next_page_number }}"><span>&raquo;</span></a></li>
            {% endif %}
          </ul>
        </nav>
    </div>
</div>
{% endblock %}



</body>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/js/jquery-3.1.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>

{% block bottom_js %}
<script type="text/javascript">

</script>
{% endblock %}

<script type="text/javascript">
    $(document).ready(function () {
        $("#navbar a[href = '{{ request.path }}']").parent().addClass("active")
        //console.log("{{ request.path }}")

        if ("{{ request.path }}" == '/')
          {
            $("#navbar a[href = '{{ request.path }}']").parent().addClass("active")
          }

    });
</script>

</html>

templates/login.html
{% extends 'index.html' %}
{% block content_left %}


    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-lg-8">
            <form class="" action="/accounts/login/" method="post">
                {% csrf_token %}
                <input type="text" name="username" placeholder="请输入用户名..."/>
                <input type="password" name="password" placeholder="请输入密码..."/>
                <br/>
                <hr/>
                <input type="submit"  class="btn btn-info" value="登录"/>
                <span style="background-color: red">{{ login_error }}</span>

            </form>

        </div>

    </div>
{% endblock %}

templates/webqq/dashboard.html
{% extends 'index.html' %}

{% block content_left %}
    {% csrf_token %}
    <div class="container">
        <div class="col-lg-8 container-mid">

            <div>

              <!-- Nav tabs -->
              <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#contact-box" aria-controls="home" role="tab" data-toggle="tab">联系人</a></li>
                <li role="presentation"><a href="#contact-group-box" aria-controls="profile" role="tab" data-toggle="tab">群组</a></li>
                <li role="presentation"><a href="#Config" aria-controls="settings" role="tab" data-toggle="tab">配置</a></li>
              </ul>

              <!-- Tab panes -->
                <div role="tabpanel" class="tab-pane active" id="contact-box">
                    <div class="row chat_box">

                        <div class="contact_list col-md-5 col-lg-3">

                            <div class="contact_list_head">
                                <input type="text"/>
                            </div>

                            <div id="contact_list" class="list-group">
{#                                这里能不能执行不知道，怎么调试#}
                                {% for contact in request.user.userprofile.friends.select_related %}
{#                                    自定义属性 contact_id  contact_type类型一对一single#}
                                    <a contact_id="{{ contact.id }}" contact_type="single" href="#" class="list-group-item">
                                        <span style="background-color: orange;" class="badge hide">0</span>
                                        {{ contact.name }}
                                    </a>
                                {% endfor %}
                            </div>



                        </div>

                        <div class="dialog_box col-md-9">
                            <div class="dialog_box_head">
{#                                <!--  这是默认值,防止出错 其实这里会出错，没有-10#}
                                <span contact_id="-10" contact_type="single">聊天室</span>
                            </div>

                            <div id="dialog_box_content" class="dialog_box_content">

                            </div>
                            <div class="dialog_box_utils">
                                img
                            </div>
                            <div class="dialog_box_sendmsg">
                                <textarea name="msg"></textarea>
                            </div>


                        </div>


                    </div>



                </div>
{#                <div role="tabpanel" class="tab-pane" id="contact-group-box">群组kkkk</div>#}
{#                <div role="tabpanel" class="tab-pane" id="Config">配置</div>#}
            </div>

        </div>
    </div>
{% endblock %}

{% block bottom_js %}



<script type="text/javascript">

    //切换对话框时，让对话内容存在
    all_dialog_sessions = {
        'single': {},
        'group': {},
    }

    //载入界面时操作
    $(document).ready(function () {

{#        ！！！！！！！！！这里不能用这个，线程开启太多！！！！！！！！！！#}
{#        //定时器，定时刷新3秒,从后台接收别人发送的消息,这个是异步的，每请求一次就会建立一个线程#}
{#        RefreshMsgs = setInterval(function () {#}
{#            //接收信息函数#}
{#            GetNewMsg();#}
{#        },3000);#}

        GetNewMsg()


        //在单击时的操作，切换聊天的人
        $("#contact_list a").click(function () {
            $(this).addClass("active");

            //这里点击有未读消息的联系人，消息数字隐藏，class消失
            $(this).children("span").addClass("hide");
            $(this).children("span").text("0");

            //他的兄弟全部去掉css
            $(this).siblings().removeClass("active");

            //调用外围自定义函数,
            SwitchChatBox(this);
        });

    });

    //与上面的自定义标签属性有关系,JS太弱了
    function SwitchChatBox(ele) {

        //从自定义标签属性中取数据
        var current_uid = $(ele).attr("contact_id");
        var current_dialog_type = $(ele).attr("contact_type");
        var current_contact_name = $(ele).text();

        //把切换时的 老session内容报存起来
        var old_session_id = $(".dialog_box_head span").attr("contact_id");
        var old_session_type = $(".dialog_box_head span").attr("contact_type");

        //把切换时的 老session内容报存起来
        Sessionhandle(old_session_id, old_session_type, 'dump');
        //切换时，新的session内容加载进来
        var current_dialog_content = Sessionhandle(current_uid, current_dialog_type, 'load');
        $(".dialog_box_content").html(current_dialog_content);

        //凑 html
        var dialog_head_html = "<span contact_id='"+current_uid+"'contact_type='"+current_dialog_type+"'>" + current_contact_name +"</span>";

        $(".dialog_box_head").html(dialog_head_html);
    }




        //jquery的一个方法
		//body下textarea的绑定一个事件，keydown敲一下键盘时，keyup键盘弹起式时
    $("body").delegate("textarea", "keydown", function(e){
            if(e.which == 13) {//敲回车键盘
                //发送 消息（敲回车后）
                var msg_text = $("textarea").val();

				//trim就是去掉空格


                if ($.trim(msg_text).length > 0) {

                    //控制台可以取到这个消息内容
                    //console.log(msg_text);
                    //发给后台
                    SendMsg(msg_text);

                    //no wait the send_msg's call confirm msg
                    AddSentMsgIntoBox(msg_text);
                    $("textarea").val('');
                }

            }
    });


    function SendMsg(msg) {
        var msg_dic = {
            'from_id': "{{ request.user.userprofile.id }}",

            //这里获取了属性信息，why？
            'to_id': $(".dialog_box_head span").attr("contact_id"),
            'contact_type': $(".dialog_box_head span").attr("contact_type"),
            'msg': msg
        };



        //这里应该用ajax做向后台发送处理的,POST就会涉及到csrf的事，这次在最大的container下面，放一个,查查这边的csrf的原因
        // post会根据token的id做判断，所以post必须要有toke值，token值已经在网页container生成了。
        //你想想 每次 提交都要有一个 token，这个太恶心，Django官方出来了个自动全局的，查查
        $.post("{% url 'chat_send_msg' %}", {'data': JSON.stringify(msg_dic), 'csrfmiddlewaretoken': $("input[name = 'csrfmiddlewaretoken']").val()}, function(callback){
            console.log(callback);
        });

    }

    //做一个保存当前会话内容，加载先前内容
    function Sessionhandle(contact_id , contact_type, action) {
        if (action == 'dump'){//保存当前的聊天记录
            var current_dialog_content = $(".dialog_box_content").html();
            all_dialog_sessions[contact_type][contact_id] = current_dialog_content;
        }
        else if(action=='load'){ //把制定的contact_id的聊天记录打印出来
            var new_dialog_content = '';
            if (all_dialog_sessions[contact_type].hasOwnProperty(contact_id)){
                new_dialog_content = all_dialog_sessions[contact_type][contact_id];
            }

            return new_dialog_content;

        }

    }

    function AddSentMsgIntoBox(msg_text){

        var msg_div = "<div class='row'><div class='pull-right'>" +
            "<span>" + "{{ request.user.userprofile.name }}" + "</span>" + " " +
            "<span>" + new Date() + "</span>" +
            "<h4><p>" + msg_text + "</p></h4>" + "</div></div>";

        //遇到坑了，JS中尽量用id来实现功能,这时候前端会直接 append很远，超过对话框，CSS样式中 要用overflow才行overflow: auto;
        $('.dialog_box_content').append(msg_div);


        //这里其实是滚动后，不显示最后一行，最号用google查询 div auto scroll to buttom
        //动画效果
         $('.dialog_box_content').animate({
            scrollTop: $('.dialog_box_content')[0].scrollHeight}, 500);

    }


    //从后台定时刷新消息
    function GetNewMsg() {

        //获取当前的收信人和名字
        var current_contact_id = $(".dialog_box_head span").attr("contact_id");
        var current_contact_name = $(".dialog_box_head span").text();


        //这里的get是不堵塞的，一直会开新线程，所以，用递归思想，放到each下面
        $.get("{% url 'get_new_msg' %}", {'uid': "{{ request.user.userprofile.id }}"}, function(callback){


            //把字符串转为JSON，前端认识的
            callback = JSON.parse(callback);

            console.log(callback);

            //把对应的消息发给对应的联系人
            $.each(callback, function (index, msg) {
               if(msg.from_id == current_contact_id){
                   var msg_div = "<div>" +
                           "<span>" + current_contact_name + "</span>" +
                           "<span>" + msg.date + "</span>" +
                           "<p>" + msg.msg+ "</p>" +
                           "</div>";
                   $(".dialog_box_content").append(msg_div);

               }
               else{ //不属于当前会话
                   var msg_count_ele = $(".contact_list a[contact_id='"+ msg.from_id +"'] span");
                   msg_count_ele.text(parseInt(msg_count_ele.text()) + 1);
                   msg_count_ele.removeClass("hide");
                    //同时把这条消息暂存在全局临时变量里(就是冒数字那些隐藏会话)
                   var msg_sender_name = $(".contact_list a[contact_id='"+ msg.from_id +"']").text();
                   var msg_div = "<div>" +
                           "<span>" + msg_sender_name + "</span>" +
                           "<span>" + msg.date + "</span>" +
                           "<p>" + msg.msg+ "</p>" +
                           "</div>";

                   var old_session_content = Sessionhandle(msg.from_id, msg.contact_type, 'load');
                   var new_session_content = old_session_content + msg_div;
                   all_dialog_sessions[msg.contact_type][msg.from_id] = new_session_content;

               }; //end else

            }); //end each
            GetNewMsg();
        }); //end get
    } //


</script>
{% endblock %}